axon:
  amqp:
    exchange: exchange
  eventhandling:
    processors:
      amqpEvents:
        source: amqpMessageSource
        mode: subscribing
spring:
  profiles:
    group:
      default-group: base, default
      dev-group: base, dev
      uat-group: base, uat
      prod-group: base, prod
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fnb}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:P@ssword789}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:P@ssword789}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: ${KEYCLOAK_PROVIDER:keycloak}
            client-id: ${KEYCLOAK_CLIENT_ID:fnb}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:HCi6FzP4YM4OkBv8qFEwSYNWbNX91MKZ}
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWT_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/userinfo}
            user-info-authentication-method: header
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
          jwk-set-uri: ${KEYCLOAK_JWT_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:umeepay_admin}
  password: ${KEYCLOAK_CLIENT_PASSWORD:Aqswde123@@}
