axon:
  distributed:
#    load-factor: 100
    jgroups:
#      bind-addr: GLOBAL
#      bind-port: 7800
#      cluster-name: Axon
      configuration-file: tcp_gossip.xml
#      gossip:
#        hosts: localhost[12001]
#        auto-start: true
spring:
  profiles:
    group:
      dev: dev, base
      uat: uat, base
      prod: prod, base
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fnb}
    username: root
    password: P@ssword789
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: ${KEYCLOAK_PROVIDER:keycloak}
            client-id: ${KEYCLOAK_CLIENT_ID:fnb}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:HCi6FzP4YM4OkBv8qFEwSYNWbNX91MKZ}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:8080/login/oauth2/code/fnb}
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWT_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/userinfo}
            user-info-authentication-method: header
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
keycloak-client:
  username: ${KEYCLOAK_CLIENT_USERNAME:umeepay_admin}
  password: ${KEYCLOAK_CLIENT_PASSWORD:Aqswde123@@}
