logging:
  level:
    com:
      zaxxer.hikari.HikariConfig: debug
    org:
      axonframework: debug
      springframework:
        security: debug
        transaction: debug
      hibernate:
        SQL: info
    vn:
      unicloud.fnb: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true