logging:
  level:
    com.zaxxer:
      hikari: debug
      hikari.HikariConfig: debug
    org.axonframework: debug
    org.springframework.security: debug
    org.dyson.dddstarter: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
