logging:
  level:
    com.zaxxer:
      hikari: trace
      hikari.HikariConfig: DEBUG
    org.axonframework: debug
    org.springframework.security: debug
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
