server:
  port: 8080
  error:
    include-exception: true
    include-stacktrace: always
axon:
  axonserver:
    enabled: false
  distributed:
    enabled: true
spring:
  datasource:
    hikari:
      pool-name: DDD-HikariPool
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
  batch:
    jdbc:
      initialize-schema: always
springdoc:
  api-docs:
    path: /api-docs
  show-actuator: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
