logging:
  level:
    com.zaxxer:
      hikari.HikariConfig: debug
    org.axonframework: debug
    org.springframework.security: debug
    org.jgroups: debug
    vn.unicloud.fnb: debug
spring:
  jpa:
    hibernate:
      ddl-auto: create
#    show-sql: true
