server:
  port: 8080
axon:
  axonserver:
    enabled: false
  distributed:
    enabled: true
    load-factor: 100
    jgroups:
      bind-addr: GLOBAL
      bind-port: 7800
      cluster-name: Axon
      configuration-file: default_tcp_gossip.xml
      gossip:
        hosts: localhost[12001]
        auto-start: false
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fnb}
    username: root
    password: P@ssword789
    hikari:
      pool-name: DDD-HikariPool
      auto-commit: true
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      minimum-idle: 3
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
    change-log: classpath:db/liquibase-changelog.yaml
  batch:
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: ${KEYCLOAK_PROVIDER:keycloak}
            client-id: ${KEYCLOAK_CLIENT_ID:fnb}
            client-secret: ${KEYCLOAK_CLIENT_SECRET:HCi6FzP4YM4OkBv8qFEwSYNWbNX91MKZ}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:8080/login/oauth2/code/fnb}
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/token}
            jwk-set-uri: ${KEYCLOAK_JWT_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/userinfo}
            user-info-authentication-method: header
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}