server:
  port:
    8089
spring:
  datasource:
    url: jdbc:postgresql://14.225.205.235:15432/rnb
    username: root
    password: P@ssword789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: 'true'
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/liquibase-changelog.yaml