server:
  port:
    8089
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/rnb
    username: root
    password: P@ssword789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/liquibase-changelog.yaml
  batch:
    jdbc:
      initialize-schema: always