server:
  port:
    8089
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: guest
    password: guest
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/fnb}
    username: root
    password: P@ssword789
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    enabled: false
    change-log: classpath:db/liquibase-changelog.yaml
  batch:
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: fnb
            client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
            authorization-grant-type: authorization_code
            redirect-uri: ${KEYCLOAK_REDIRECT_URI:http://localhost:8080/login/oauth2/code/fnb}
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
            authorization-uri: ${KEYCLOAK_AUTHORIZATION_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/auth}
            token-uri: ${KEYCLOAK_TOKEN_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/token}
            user-info-uri: ${KEYCLOAK_USERINFO_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/userinfo}
            jwk-set-uri: ${KEYCLOAK_JWT_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb}
          jwk-set-uri: ${OAUTH2_JWK_SET_URI:https://idp-dev.hcm.unicloud.ai/realms/fnb/protocol/openid-connect/certs}
